version: "3"

services:
  app:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.runtime/nginx/logs:/var/log/nginx/
    links:
      - php
      - database
      - mailhog

  php:
    image: php:7-fpm
    container_name: PHP7
    volumes:
      - ./:/var/www/app

  database:
    image: mariadb
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=dbase
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    volumes:
      - ./.runtime/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_USER=dbuser
      - PMA_PASSWORD=dbpass
      - PHP_UPLOAD_MAX_FILESIZE=1G
      - PHP_MAX_INPUT_VARS=1G
    restart: always
    ports:
     - 8001:80
    volumes:
     - /sessions

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
